### ISSUE TITLE
[flattop] Alternative light interception models (flat top, PPA)

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#417]
## Problem statement

Owner: @dfalster 

As a user running simulations, I may want to run model with alternative light models, as these could offer different resolution and speed. 

Elaboration:  The ff16 model currently uses deep crown model. Lily Dun's hours explored alternatives, including a flat top and PPA (perfect plasticity Appoximation) in 3D simulations. Most other DGVMs use one of those. 

A while back @aornugent  programmed up a version of the PPA light model. (see branch https://github.com/traitecoevo/plant/tree/ff16-ppa). Currently it's implemented as a new strategy variant of ff16, but perhaps should be an option for FF16?

In the end, we may have:

* deep crown
* flat top
* PPA
* New model 

Obviously, these aren't full implementations, as we're not utilising the simplification to speed up the calculations, either through analytic integration of density (best), or simplifying calculation of the light env. These could be added, but we'd need to extend the light environment to have different options. 

## Issues ##

- [ ] https://github.com/traitecoevo/plant/issues/XXX

## Acceptance criteria ##

Given a simulation, we can

- [ ] specify alternative light models

**Comment by dfalster** [comment]
## Progress report — alternative light models implemented on branch [`shading-method`](https://github.com/traitecoevo/plant/tree/shading-method)

Alternative light-interception models are now selectable at runtime via a single control parameter, addressing the acceptance criterion *"specify alternative light models"*. Following the suggestion in the issue, PPA (and the others) are implemented as **options for FF16**, not separate strategy variants.

### How to use

```r
ctrl <- Control()
ctrl$shading_model <- "flat-top"   # see options below
run_scm(patch, ctrl = ctrl)
```

**FF16** supports six models; **TF24** supports three (no PPA):

| `shading_model` | assimilation | competition / light profile | FF16 | TF24 |
|---|---|---|:--:|:--:|
| `deep-crown` | integrate photosynthesis over crown depth | smooth Yokozawa | ✅ default | ✅ |
| `average-light` | integrate the *light* over depth → one photosynthesis eval | smooth Yokozawa | ✅ | ✅ **default** |
| `flat-top` | single eval at crown centre | smooth Yokozawa | ✅ | ✅ |
| `ppa` | single eval at crown centre | **stepped** (discrete canopy layers) | ✅ | ✕ |
| `flat-top-box` | single eval at crown centre | **hard step** (naive) | ✅ | ✕ |
| `flat-top-soft-box` | single eval at crown centre | smoothed box (naive) | ✅ | ✕ |

The model is resolved **once** in `prepare_strategy()` into a function pointer (mirroring `CanopyShape::select_pow_eta`), so there is **no per-call string comparison on the hot path**. The shared `Control` default is `""` = "each strategy's own default" (FF16→deep-crown, TF24→average-light), so existing results for both are unchanged bit-for-bit.

### Key results

**Speed (FF16, single-species patch):**
- `deep-crown` — **no measurable regression vs develop** (the dispatch is one indirect call per `assimilation`, outside the quadrature loop).
- `flat-top` ~0.6× deep-crown (skips the crown-depth quadrature).
- `ppa` — ~3× *slower* on the adaptive solver (its near-stepped profile is stiff → many more steps), but ~0.6× on a *fixed* schedule (cheap per step). So PPA's cost is step-count, not per-step work.

**`average-light`** captures the within-crown light feedback but collapses photosynthesis to one call per plant. Minor for FF16; **important for TF24**, whose coupled stomatal/hydraulic optimisation is expensive — this is why it's TF24's default. By Jensen's inequality (saturating photosynthesis) it slightly overestimates vs deep-crown.

**Invasion fitness (the demanding test).** Fitness landscapes (log R0 of mutants vs LMA against a cached resident):
- `deep-crown`, `average-light`, `flat-top` → **smooth**, and the cheap approximations track deep-crown closely.
- `ppa` → **jagged** (sharp discontinuity where a small trait change flips which layer the mutant ends in).

The lesson: invasion fitness needs the shading a plant experiences to vary **continuously with size**, which depends on continuity of the light *profile*, not the assimilation method. This is also why `flat-top` (smooth competition, crude assimilation) is fine but the two naive box variants are not:
- `flat-top-box` (hard-step competition) → patch light profile is discontinuous → the adaptive light-environment spline can't be built → **the model won't run at all**.
- `flat-top-soft-box` (continuous but mis-shaped competition) → runs, but gives a **biased** fitness landscape (~2.4× the divergence from deep-crown that correct flat-top shows).

So: a crude **assimilation** approximation is tolerable, but the shade each plant **casts** must be both continuous and the right shape.

### Numerical note on PPA
A literal PPA step is non-differentiable, which defeats the adaptive error-controlled ODE solver (it shrinks the step indefinitely) and overshoots to non-finite values under fixed steps. Two control params make it tractable:
- `ppa_layer_optical_depth` (default 0.5 ≈ 1 LAI/layer at `k_I=0.5`) — layer thickness.
- `ppa_layer_smoothing` (default 0.3) — C¹ cubic smoothing of layer boundaries, so the profile is differentiable and integrates on the normal adaptive solver; adaptive and fixed-step solutions then agree.

### Deliverables
- C++: `ShadingModel` enum + dispatch in `CanopyShape`, `FF16_Strategy`, `TF24_Strategy`; stepped/smoothed PPA profile in `FF16_Environment`; `Environment::set_shading_model` hook wired from the `Patch` ctor.
- New vignette **"Canopy shading methods"** (`vignettes/canopy_methods.Rmd`): size-distribution & LAI dynamics, vertical light profiles, both speed tables, the mutant-fitness comparison, and the "getting the competition profile right" demonstration.
- Tests: `tests/testthat/test-canopy-methods.R` (63 tests) covering defaults, per-model invariants (uniform-light agreement, Jensen, baseline reproduction), PPA discretisation/smoothing, the box counterexamples, and TF24 rejections. Full suite green.

### Not yet done (future work)
- **Analytic integration of the size-density** for speed (the "best" simplification noted in the issue) — not attempted; the light environment is still built by the same adaptive spline for all models (PPA only differs by flooring optical depth at read time).
- **TF24 `deep-crown`** runs the hydraulic optimisation once per crown-depth quadrature node (~8× cost) — correct but not optimised.
- @aornugent's [`ff16-ppa`](https://github.com/traitecoevo/plant/tree/ff16-ppa) branch is effectively superseded by the in-strategy PPA option here, but worth cross-checking the layer definition against that implementation.

Happy to open a PR against `develop` when ready.

**Comment by dfalster** [comment]
### Follow-up: the shading model changes the *equilibrium stand*, not just per-stand fitness

Worth flagging a result that came out of putting the mutant-fitness residents at their **demographic equilibrium** (seed rain where R0 = 1, found by iterating `birth_rate <- run_scm(...)$offspring_production` — converges in ~5 runs). The equilibrium seed rain differs markedly by model for the same trait (FF16, lma = 0.0825, `max_patch_lifetime = 50`):

| model | equilibrium seed rain |
|---|---|
| deep-crown | 1.66 |
| average-light | 2.18 |
| flat-top | 2.19 |
| flat-top-soft-box | 3.10 |
| **ppa** | **18.84** (~11× deep-crown) |

So PPA's brighter layered light doesn't just shift assimilation — it predicts a *qualitatively denser* equilibrium stand.

The vignette now runs **two** mutant-fitness comparisons to separate these effects:
1. **same seed rain** (all models seeded at the deep-crown equilibrium) — isolates the shading model's effect on a fixed stand;
2. **each at its own equilibrium** — the self-consistent picture.

The landscapes diverge *more* under (2) than (1), because the different equilibrium densities compound with the different light treatment. PPA is jagged under both and wildly so at its own (denser) equilibrium. Net: a cheap shading model can mislead evolutionary predictions in two compounding ways — a different fitness gradient in a given stand, and a different stand to begin with.

(Branch [`shading-method`](https://github.com/traitecoevo/plant/tree/shading-method) updated; equilibria hardcoded in the vignette to keep build fast.)

**Comment by dfalster** [comment]
### Progress — alternative shading models implemented (PR #490)

The core of this epic is delivered on `shading-method` → **#490**. Alternative
light models are now selectable on FF16 and TF24 via a single runtime control,
`control$shading_model` (no longer a separate strategy variant):

- **`deep-crown`** — original FF16 (smooth Yokozawa, assimilation integrated over crown depth)
- **`mean-light`** — smooth shade, one assimilation eval at the mean light
- **`crown-centre`** — smooth shade, one eval at the crown centre
- **`flat-top-box`** / **`flat-top-soft-box`** — box (thin-layer) shade, hard vs C1-smoothed
- **`ppa`** — perfect-plasticity stepped layers (`ppa_layer_optical_depth`, `ppa_layer_smoothing`)

Dispatch is resolved once at strategy setup; deep-crown is unchanged with no
speed regression. New `canopy_methods.Rmd` vignette documents the models and the
realism/speed trade-off.

**Acceptance criteria**
- [x] specify alternative light models

**Key finding on the discontinuous variants.** The literal field discretisations
are not well-posed continuous-time models:
- *PPA hard step* (`ppa_layer_smoothing = 0`) — the adaptive solver refuses it;
  forcing it to run with fixed-step Euler (#489) produces a **grid-dependent**
  result (selection-gradient sign pattern flips daily vs half-daily; resident
  dynamics don't converge under refinement).
- *flat-top-box* — fails *upstream* in the environment-interpolation refinement
  (discontinuous in height), so fixed-step can't rescue it either.

So the **smoothed** variants are the only defensible report. Demonstrated in
`make_figure_gridartifact.R` and the `time_stepping.Rmd` vignette.

Leaving this epic open for the not-yet-done parts (analytic density integration /
light-env speedups noted in the problem statement); the model-selection criterion
is met.
