### ISSUE TITLE
[plantviz] Visualisations of dynamic/growing patches

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#429]
## Problem statement

As a researcher, I would love to be able to visualise dynamically growing patches and metapopulations of plants. 

Elaboration:  These might extend the kinds of figures presented in Falster et al 2018, which generated with custom R package using rgl:

![](https://www.pnas.org/cms/10.1073/pnas.1610206114/asset/8384bad5-2a5f-4e19-90d8-6a8c159abceb/assets/graphic/pnas.1610206114fig01.jpeg)
)

Owner: 

## Issues ##

- [ ] https://github.com/traitecoevo/plant/issues/XXX

## Acceptance criteria ##

Given a simulation of individuals /  patches / metapopulations, we can create

- [ ] snapshots of system
- [ ] animations of system
